### ISSUE TITLE
Can we get a new release?

### ISSUE THREAD

**Issue by RubenKelevra** [markfeit/duplicacy-scripts#10]
There have been some fixes in the master, which are not released yet. Are they still considered unstable?

If not, I would like to encourage you to create a new release containing them :)

**Comment by markfeit** [comment]
Generally, what's in `master` is stable or reaches stability very quickly since I use this to back up my own systems.  If `CONFIG_AUTO_UPDATE` in `etc/settings` is enabled, the scripts will automatically pull the contents of `master` and start using that.

But it's been awhile since the last release and I don't have any changes in the pipeline, so I'll publish a new one.

**Comment by RubenKelevra** [comment]
@markfeit thanks! I was thinking of creating a package for Arch Linux and fetching a master from git for a backup script doesn't feel right :)

**Comment by markfeit** [comment]
I'll try to remember do do releases as I add new features.  I guess if you're going to package it, it would make sense to ship it with auto update turned off.
