### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by skidvd** [markfeit/duplicacy-scripts#2]
Hi Mark,

Thanks for putting this together - very nice!

I have a few questions:

1) If I need to update a few of the actual commands (take backup for example) to include a different set of duplicacy options, will these be subsequently overwritten with an update?  

2) Same question as 1) about cron jobs?

3) Is there any way to configure install/update to skip the cron job updates if you wanted to tailor them locally?

TIA!

**Comment by markfeit** [comment]
I could make the switches configurable if you don't mind testing it out.  Let me know what your use cases are and I'll try to come up with a good, general-purpose solution.

For everything else, the easiest thing to do might be to fork this repository, do your customization in the fork and merge/deconflict my changes as I release them.  That way, you could turn automatic updating on and use your fork as the origin version for what's installed on your systems.

The one hitch right now is that the URL for the git repo is hardwired into the Makefile that does the initial setup.  That should be easy to fix by detecting whether or not the top of the source tree is a Git repository and pulling the origin out of that.  You can work around it in the mean time by changing the URL to point at your fork.

By the way, [the as-shipped configuration has updating turned off](https://github.com/markfeit/duplicacy-scripts/blob/338a2ba2cb7edc51140ced690f0c32f4f87269f2/etc/settings#L11) for that reason.  Cron will still run `update` every night, but its first action will be seeing that it's not configured to run and exit.  I use the repository as a conduit for upgrades to my own systems because I'm opportunistically lazy like that.  :-)

**Comment by skidvd** [comment]
Thanks Mark, good suggestion re forking...

**Comment by skidvd** [comment]
BTW, I notice that you delete the .duplicacy dir invoking the init command in the init-storage script.  Are you relying on someone to pass the -pref-diroption to the init-storage script, or am I missing that somewhere?

**Comment by markfeit** [comment]
That script doesn't get used anywhere; I think I'd intended to use it for something and never did.  Since all of the files `duplicacy init` builds are already established, it's not needed.

All I have to do is build a symlink during `make install` or during a restore.  In the latter case, I get rid of it at the end so there's no mistaking the restore directory for one that gets backed up.
